grumphp:
    hide_circumvention_tip: true
    process_timeout: 60
    ascii:
        failed: grumphp-grumpy.txt
        succeeded: grumphp-happy.txt
    parallel:
        enabled: true
        max_workers: 32
    fixer:
        enabled: true
        fix_by_default: true
    tasks:
        composer: ~
#        composer_require_checker: ~ TODO - research how this works
        git_blacklist:
            keywords:
                - "dd\\("
                - "dump\\("
            regexp_type: E
            match_word: true
            triggered_by:
              - 'php'
        git_branch_name:
            blacklist:
                - "master"
                - "develop"
            allow_detached_head: false
        git_commit_message:
            enforce_capitalized_subject: true
            enforce_no_subject_punctuations: true
            max_body_width: 250
            max_subject_width: 72
            matchers:
                Prefix is required: /^(Add|Doc|Fix|Move|Refactor|Remove|Revert|Update|Upgrade|Downgrade|WIP)+/
        yamllint: ~
        xmllint: ~
        jsonlint: ~
        phplint: ~
        phpstan:
          memory_limit: '-1'
        phpcs:
          standard:
            - 'vendor/libaro-io/quality-tools/config/phpcs.xml'
          severity: 5
          error_severity: 5
          warning_severity: 5
          encoding: utf-8
          ignore_patterns:
            - 'database/migrations'
            - 'public/index'
            - 'resources/views'
            - 'resources/lang'
            - 'routes'
            - 'vendor'
            - '_ide_helper.php'
            - '_ide_helper_models.php'
            - '.phpstorm.meta.php'
        phpmd:
          exclude:
            - 'database/migrations'
            - 'tests'
            - 'vendor'
            - '_ide_helper.php'
            - '_ide_helper_models.php'
            - '.phpstorm.meta.php'
          ruleset:
            - 'vendor/libaro-io/quality-tools/config/phpmd.xml'
        securitychecker_enlightn:
          lockfile: ./composer.lock
          run_always: false
    testsuites: []
    extensions: []
